name: Mirror

env:
  MIRROR_REPO: "git@github.com:EpitechPromo2026/G-EIP-700-RUN-7-1-eip-denis.maillot.git"

on:
  # You can only pull request to main since it only contain final version of the code when all tests passed and build is successful
  push:
    branches:
    - dev

  pull_request:
    branches:
    - main
    - dev

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # - uses: ./.github/actions/test

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      # - uses: ./.github/actions/build/linux
  
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      # - uses: ./.github/actions/build/windows

  mirror:
    needs:
      - test
      - build-windows
      - build-linux
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ env.MIRROR_REPO }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
