name: Mirror

env:
    MIRROR_REPO: "git@github.com:EpitechPromo2026/G-EIP-700-RUN-7-1-eip-denis.maillot.git"

on:
    # You can only pull request to main since it only contain final version of the code when all tests passed and build is successful
    push:
        branches:
        - dev

    pull_request:
        branches:
        - main
        - dev

jobs:
  test:
    name: Tests
    steps:
      - uses: ./.github/actions/test

  build:
    name: Build
    steps:
      - uses: ./.github/actions/build/windows
      - uses: ./.github/actions/build/linux

  mirror:
    needs:
      - test
      - build
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ env.MIRROR_REPO }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
